export const screens = {
    Splash: 'Splash',
    PanDetails: 'PanDetails',
    KYC: 'KYC',
    CaptureAdhaar: 'CaptureAdhaar',
    CaptureSelfie: 'CaptureSelfie',
    HomeScreen: 'HomeScreen',
    ApplicantDetails: 'ApplicantDetails',
    ApplyForLoan: 'ApplyForLoan',
    Calculators: 'Calculators',
    StatusCheck: 'StatusCheck',
    AadharBack: 'AadharBack',
    AadharDocUplaod: 'AadharDocUplaod',
    AadharFront: 'AadharFront',
    AadharNumber: 'AadharNumber',
    Documentsverified: 'Documentsverified',
    SelfPicture: 'SelfPicture',
    Eligiblity: 'Eligiblity',
    InPrincipleSection: 'InPrincipleSection',
    LoanDetail: 'LoanDetail',
    PancardNumber: 'PancardNumber',
    PandcardDetails: 'PandcardDetails',
    NoInternet: 'NoInternet',
    ErrorScreen:'ErrorScreen',
    CongratulationScreen:'CongratulationScreen',
    Eligibility:"Eligibility",
    ProfileImageScreen: "ProfileImageScreen",
    Sanction:"Sanction",
    LoanDetails:"LoanDetails",
  };