export const screens = {
    Splash: 'Splash',
    PanDetails: 'PAN and KYC',
    MyTickets: 'My Tickets',
    KYC: 'Adhaar KYC',
    CaptureAdhaar: 'CaptureAdhaar',
    CaptureSelfie: 'Capture Selfie',
    HomeScreen: 'HomeScreen',
    ApplicantDetails: 'ApplicantDetails',
    ApplyForLoan: 'ApplyForLoan',
    Calculators: 'Calculators',
    StatusCheck: 'StatusCheck',
    AadharBack: 'AadharBack',
    AadharDocUplaod: 'AadharDocUplaod',
    AadharFront: 'AadharFront',
    AadharNumber: 'AadharNumber',
    Documentsverified: 'Documentsverified',
    SelfPicture: 'SelfPicture',
    Eligiblity: 'Eligiblity',
    InPrincipleSection: 'InPrincipleSection',
    PancardNumber: 'PancardNumber',
    PandcardDetails: 'PandcardDetails',
    NoInternet: 'NoInternet',
    ErrorScreen:'ErrorScreen',
    CongratulationScreen:'CongratulationScreen',
    Eligibility:"Eligibility",
    KYCDocuments:"KYCDocuments",
    ProfileImageScreen: "ProfileImageScreen",
    Sanction:"Sanction",
    LoanDetails:"Loan Details",
    RaiseTicket:'RaiseTicket',
    CreateTicket: "CreateTicket",
    FAQ:"FAQ",
    TrackTicket: 'TrackTicket',
    PayNow: 'PayNow',
    StatusCheck: "StatusCheck",
    EmiCalculator: "EmiCalculator",
    CurrentAddress: "CurrentAddress",
    OtpScreen: "OtpScreen",
    PinCodeVerify: "PinCodeVerify",
    Profile: 'Profile',
    Dummy: 'Dummy',
    Services:'services',
    ServiceOtp: 'ServiceOtp'
  };