export const screens = {
  Splash: "Splash",
  PanDetails: "PAN and KYC",
  MyTickets: "My Tickets",
  KYC: "Adhaar KYC",
  CaptureAdhaar: "CaptureAdhaar",
  CaptureSelfie: "Capture Selfie",
  HomeScreen: "HomeScreen",
  ApplicantDetails: "ApplicantDetails",
  ApplyForLoan: "ApplyForLoan",
  Calculators: "Calculators",
  StatusCheck: "StatusCheck",
  AadharBack: "AadharBack",
  AadharDocUplaod: "AadharDocUplaod",
  AadharFront: "AadharFront",
  AadharNumber: "AadharNumber",
  Documentsverified: "Documentsverified",
  SelfPicture: "SelfPicture",
  InPrincipleSection: "InPrincipleSection",
  PancardNumber: "PancardNumber",
  PandcardDetails: "PandcardDetails",
  NoInternet: "NoInternet",
  ErrorScreen: "ErrorScreen",
  CongratulationScreen: "CongratulationScreen",
  Eligibility: "Eligibility",
  KYCDocuments: "KYCDocuments",
  ProfileImageScreen: "ProfileImageScreen",
  Sanction: "Sanction",
  LoanDetails: "Loan Details",
  RaiseTicket: "RaiseTicket",
  CreateTicket: "CreateTicket",
  FAQ: "FAQ",
  TrackTicket: "TrackTicket",
  PayNow: "PayNow",
  StatusCheck: "Loan Status",
  EmiCalculator: "EMI Calculator",
  CurrentAddress: "CurrentAddress",
  OtpScreen: "OtpScreen",
  PinCodeVerify: "PinCodeVerify",
  Profile: "Profile",
  Dummy: "Dummy",
  Services: "services",
  ServiceOtp: "ServiceOtp",
  LoginComponent: "LoginComponent",
  CoApplicant: "CoApplicant",
  ConsentScreen: 'ConsentScreen',
  SystemLoanDetails: 'SystemLoanDetails'
};
