import { MD3LightTheme as DefaultTheme } from "react-native-paper";
import { colors } from ".";

const customTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: "rgba(46, 82, 161, 1)",
    primaryContainer: "#E1F3FF",
    primaryShadow: "rgba(105, 87, 211, 0.3)",
    surfaceVariant: "#D7E7F4",
    surface: "#0076C7",
    background: "#FFFFFF",
    seconderyBackground: "rgba(254, 249, 235, 1)",
    textInputBackground: "#FFFFFF",
    error: "rgba(232, 41, 45, 1)",
    errorContainer: "rgba(251, 226, 226, 1)",
    success: "rgba(15, 157, 88, 1)",
    primaryText: "#000000",
    seconderyText: "rgba(124, 126, 139, 1)",
    elevation: {
      level3: "rgba(0, 0, 0, 0.25)",
      // level0: "#E6F4FF",
      // level1: "#E6F4FF",
      // level2: "#E6F4FF",
      // level4: "#E6F4FF",
      // level5: "#E6F4FF",
    },
  },
  shape: {
    ...DefaultTheme.shape,
    roundness: 6,
  },
  fonts: {
    ...DefaultTheme.fonts,
    smallText: {
      fontFamily: "Nunito-Regular",
      fontWeight: "normal",
      fontSize: 12,
      color: '#000000',
    },
    smallLightText: {
      fontFamily: "Nunito-Regular",
      fontWeight: "normal",
      fontSize: 12,
      color: 'rgba(124, 126, 139, 1)',
    },
    regularText: {
      fontFamily: "Nunito-Regular",
      fontWeight: "normal",
      fontSize: 14,
      color: '#000000',
    },
    regularLightText: {
      fontFamily: "Nunito-Regular",
      fontWeight: "normal",
      fontSize: 14,
      color: 'rgba(124, 126, 139, 1)',
    },
    mediumText: {
      fontFamily: "Nunito-Regular",
      fontWeight: "bold",
      fontSize: 14,
      color: '#000000',
    },
    default: {
      fontFamily: "Nunito-Regular",
      fontWeight: "normal",
      letterSpacing: 0,
      color: '#000000',
    },
    titleSmall: {
      fontFamily: "Nunito-Bold",
      fontSize: 18,
      letterSpacing: 0.15,
      lineHeight: 24,
      color: '#000000',
    },
    titleMedium: {
      fontFamily: "Nunito-Bold",
      fontSize: 20,
      letterSpacing: 0.15,
      lineHeight: 24,
      color: '#000000',
    },
    titleLarge: {
      fontFamily: "Nunito-Bold",
      fontSize: 22,
      letterSpacing: 0,
      lineHeight: 28,
      color: '#000000',
    },
    bodySmall: {
      fontFamily: "Nunito-Regular",
      fontSize: 12,
      fontWeight: "400",
      letterSpacing: 0.4,
      lineHeight: 16,
      color: '#000000',
    },
    bodyRegular: {
      fontFamily: "Nunito-Regular",
      fontSize: 16,
      fontWeight: "600",
      letterSpacing: 0.4,
      lineHeight: 20,
      color: '#000000',
    },
    bodyBold: {
      fontFamily: "Nunito-Bold",
      fontSize: 18,
      letterSpacing: 0.4,
      lineHeight: 22,
      color: '#000000',
    },
    inputText: {
      fontFamily: "Nunito-Regular",
      fontSize: 16,
      lineHeight: 20,
      color: '#000000',
    },
    buttonText: {
      fontFamily: "Nunito-Bold",
      fontSize: 18,
      lineHeight: 25,
      color: colors.white,
    },
    seconderyButtonText: {
      fontFamily: "Nunito-Bold",
      fontSize: 18,
      lineHeight: 25,
      color: "rgba(46, 82, 161, 1)",
    },
    labelSmall: {
      fontFamily: "Nunito-Regular",
      fontSize: 14,
      lineHeight: 16,
      color: 'rgba(136, 136, 136, 1)',
    },
    labelMedium: {
      fontFamily: "Nunito-Regular",
      fontSize: 16,
      lineHeight: 20,
      color: 'rgba(136, 136, 136, 1)',
    },
    labelLarge: {
      fontFamily: "Nunito-Regular",
      fontSize: 14,
      lineHeight: 20,
      color: 'rgba(136, 136, 136, 1)',
    },
    headlineSmall: {
      fontFamily: "Nunito-Regular",
      fontSize: 24,
      fontWeight: "400",
      letterSpacing: 0,
      lineHeight: 32,
      color: '#000000',
    },
    headlineMedium: {
      fontFamily: "Nunito-Regular",
      fontSize: 28,
      fontWeight: "400",
      letterSpacing: 0,
      lineHeight: 36,
      color: '#000000',
    },
    headlineLarge: {
      fontFamily: "Nunito-Regular",
      fontSize: 32,
      fontWeight: "400",
      letterSpacing: 0,
      lineHeight: 40,
      color: '#000000',
    },
  },
};

export default customTheme;
